#!/usr/bin/env bash
# Compiles sphere_surface_mesh_stub_for_test.slang → WGSL (two entry points),
# then writes both shaders as a JS module for the Electron/Three.js bridge.
#
# Run from any directory:
#   bash slang/native/scripts/build-sphere-wgsl.sh
#
# Output:
#   slang/native/examples/simplical-visualiser/app/renderer/slang_bridge/sphere_mesh_wgsl.js
set -euo pipefail

SLANGC="${SLANGC:-/dataneura/gpu-experimentations/experiments/20_slang_shaders/slang/build/RelWithDebInfo/bin/slangc}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
NATIVE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"   # slang/native/

FIXTURE="$NATIVE_DIR/polygonisers/fixtures/sphere_surface_mesh_stub_for_test.slang"
OUT="$NATIVE_DIR/examples/simplical-visualiser/app/renderer/slang_bridge/sphere_mesh_wgsl.js"

echo "slangc: $SLANGC"
echo "fixture: $FIXTURE"
echo "output:  $OUT"

tmp_v="$(mktemp /tmp/sphere_vertices.XXXXXX.wgsl)"
tmp_f="$(mktemp /tmp/sphere_faces.XXXXXX.wgsl)"
trap "rm -f '$tmp_v' '$tmp_f'" EXIT

"$SLANGC" "$FIXTURE" -target wgsl -entry genVertices -stage compute -o "$tmp_v"
echo "  genVertices → $tmp_v  ($(wc -c < "$tmp_v") bytes)"

"$SLANGC" "$FIXTURE" -target wgsl -entry genFaces -stage compute -o "$tmp_f"
echo "  genFaces    → $tmp_f  ($(wc -c < "$tmp_f") bytes)"

VERTICES_WGSL="$(cat "$tmp_v")"
FACES_WGSL="$(cat "$tmp_f")"

cat > "$OUT" <<JSEOF
// AUTO-GENERATED by slang/native/scripts/build-sphere-wgsl.sh — do not edit.
// Re-run the script after changing sphere_surface_mesh_stub_for_test.slang.
//
// Slang source: slang/native/polygonisers/fixtures/sphere_surface_mesh_stub_for_test.slang
// Compiled with: slangc <fixture> -target wgsl -entry <entryPoint> -stage compute
//
// Binding layout (both shaders share binding 0 for params):
//   @binding(0) @group(0)  gParams   — uniform  (SphereParams, std140, 32 bytes)
//   @binding(1) @group(0)  gVertices — storage  (array<f32>, genVertices only)
//   @binding(2) @group(0)  gFaces    — storage  (array<u32>, genFaces only)
//
// SphereParams std140 offsets (matches JS DataView writes in gpu_compute_bridge.js):
//   byte  0 — radius (f32)
//   byte  4 — cx     (f32)
//   byte  8 — cy     (f32)
//   byte 12 — cz     (f32)
//   byte 16 — M      (u32)
//   byte 20 — N      (u32)
//   byte 24 — _pad0  (u32)
//   byte 28 — _pad1  (u32)

export const VERTICES_WGSL = /* wgsl */\`
${VERTICES_WGSL}
\`;

export const FACES_WGSL = /* wgsl */\`
${FACES_WGSL}
\`;
JSEOF

echo "Written: $OUT"
