#!/usr/bin/env bash
# Compiles .slang to .js
#     Compiles all polygonisation fixtures from .slang to WGSL and writes JS modules.
#     then writes both shaders as a JS module for the Electron/Three.js bridge.
#     Output:
#               slang/native/examples/simplical-visualiser/app/renderer/slang_bridge/generated/
#               *_mesh_wgsl.js
#               as $GEN_DIR
#
# Fixtures compiled:
#   sphere_surface_mesh_stub_for_test.slang  → generated/sphere_mesh_wgsl.js
#   hemisphere_sharp_edge_fixture.slang      → generated/hemisphere_mesh_wgsl.js
#
# Run from any directory:
#   bash slang/native/scripts/build-sphere-wgsl.sh

# The .slang files: (polygoniser, their fixtures)
#       $FIXTURE_DIR
#
# The implicit functions .slang files,
#       via include dires, via `-I` flag, $IMPLICIT_DIR,
#       is: `slang/native/implicit_function/`
#       for modules (UnitSphere, HalfSpace, etc.)
set -euo pipefail

SLANGC="${SLANGC:-/dataneura/gpu-experimentations/experiments/20_slang_shaders/slang/build/RelWithDebInfo/bin/slangc}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
NATIVE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"   # slang/native/
IMPLICIT_DIR="$NATIVE_DIR/implicit_function"
FIXTURE_DIR="$NATIVE_DIR/polygonisers/fixtures"
GEN_DIR="$NATIVE_DIR/examples/simplical-visualiser/app/renderer/slang_bridge/generated"

mkdir -p "$GEN_DIR"

echo "slangc:   $SLANGC"
echo "includes: $IMPLICIT_DIR"
echo "output:   $GEN_DIR"
echo ""

# Helper: compile one entry to a temp file; print its size.
compile_entry() {
    local fixture="$1" entry="$2" out="$3"
    "$SLANGC" -I "$IMPLICIT_DIR" "$fixture" -target wgsl -entry "$entry" -stage compute -o "$out"
    echo "  $entry  → $(wc -c < "$out") bytes"
}

# ---------------------------------------------------------------------------
# Sphere fixture  (3 entries)
# ---------------------------------------------------------------------------
SPHERE="$FIXTURE_DIR/sphere_surface_mesh_stub_for_test.slang"
OUT_SPHERE="$GEN_DIR/sphere_mesh_wgsl.js"
echo "=== Sphere fixture ==="

t_sv="$(mktemp /tmp/sphere_verts.XXXXXX.wgsl)"
t_sf="$(mktemp /tmp/sphere_faces.XXXXXX.wgsl)"
t_sn="$(mktemp /tmp/sphere_norms.XXXXXX.wgsl)"
trap "rm -f '$t_sv' '$t_sf' '$t_sn'" EXIT

compile_entry "$SPHERE" genVertices "$t_sv"
compile_entry "$SPHERE" genFaces    "$t_sf"
compile_entry "$SPHERE" genNormals  "$t_sn"

SPHERE_V="$(cat "$t_sv")"
SPHERE_F="$(cat "$t_sf")"
SPHERE_N="$(cat "$t_sn")"

cat > "$OUT_SPHERE" <<JSEOF
// AUTO-GENERATED by slang/native/scripts/build-sphere-wgsl.sh — do not edit.
// Source: polygonisers/fixtures/sphere_surface_mesh_stub_for_test.slang
//
// Binding layout per entry (each WGSL only declares bindings it uses):
//   genVertices  @binding(0)=params  @binding(1)=vertices
//   genFaces     @binding(0)=params  @binding(2)=faces
//   genNormals   @binding(0)=params  @binding(1)=vertices(read)  @binding(3)=normals
//
// SphereParams std140 byte offsets:
//   0:radius  4:cx  8:cy  12:cz  16:M  20:N  24:_pad0  28:_pad1
//
// Dispatch (genNormals must follow genVertices):
//   genVertices  ceil((M+1)/8) × ceil((N+1)/8) × 1
//   genFaces     ceil(M/8)     × ceil(N/8)     × 1
//   genNormals   ceil((M+1)/8) × ceil((N+1)/8) × 1

export const VERTICES_WGSL = /* wgsl */\`
${SPHERE_V}
\`;

export const FACES_WGSL = /* wgsl */\`
${SPHERE_F}
\`;

export const NORMALS_WGSL = /* wgsl */\`
${SPHERE_N}
\`;
JSEOF
echo "  → $OUT_SPHERE"
echo ""

# ---------------------------------------------------------------------------
# Hemisphere fixture  (4 entries)
# ---------------------------------------------------------------------------
HEMI="$FIXTURE_DIR/hemisphere_sharp_edge_fixture.slang"
OUT_HEMI="$GEN_DIR/hemisphere_mesh_wgsl.js"
echo "=== Hemisphere fixture ==="

t_hcg="$(mktemp /tmp/hemi_capgeom.XXXXXX.wgsl)"
t_hdg="$(mktemp /tmp/hemi_diskgeom.XXXXXX.wgsl)"
t_hcf="$(mktemp /tmp/hemi_capfaces.XXXXXX.wgsl)"
t_hdf="$(mktemp /tmp/hemi_diskfaces.XXXXXX.wgsl)"
t_hom="$(mktemp /tmp/hemi_outmeta.XXXXXX.wgsl)"
trap "rm -f '$t_sv' '$t_sf' '$t_sn' '$t_hcg' '$t_hdg' '$t_hcf' '$t_hdf' '$t_hom'" EXIT

compile_entry "$HEMI" genCapGeom      "$t_hcg"
compile_entry "$HEMI" genDiskGeom     "$t_hdg"
compile_entry "$HEMI" genCapFaces     "$t_hcf"
compile_entry "$HEMI" genDiskFaces    "$t_hdf"
compile_entry "$HEMI" getOutputMetadata "$t_hom"

HEMI_CG="$(cat "$t_hcg")"
HEMI_DG="$(cat "$t_hdg")"
HEMI_CF="$(cat "$t_hcf")"
HEMI_DF="$(cat "$t_hdf")"
HEMI_OM="$(cat "$t_hom")"

cat > "$OUT_HEMI" <<JSEOF
// AUTO-GENERATED by slang/native/scripts/build-sphere-wgsl.sh — do not edit.
// Source: polygonisers/fixtures/hemisphere_sharp_edge_fixture.slang
//
// Binding layout per entry (each WGSL only declares bindings it uses):
//   genCapGeom      @binding(0)=params  @binding(1)=vertices  @binding(3)=normals
//   genDiskGeom     @binding(0)=params  @binding(1)=vertices  @binding(3)=normals
//   genCapFaces     @binding(0)=params  @binding(2)=faces
//   genDiskFaces    @binding(0)=params  @binding(2)=faces  @binding(4)=sharpEdges  @binding(5)=sharpCorners
//   getOutputMetadata  @binding(0)=params  @binding(6)=resultsMetadata
//
// ShapeSharpFeatures std430 layout (flat u32 array at binding 6):
//   [0]=numVerts  [1]=numFaces  [2]=numNormals  [3]=shape.numSharpEdges  [4]=shape.numSharpCorners
//
// HemiParams std140 byte offsets (same as SphereParams):
//   0:radius  4:cx  8:cy  12:cz  16:M  20:N  24:_pad0  28:_pad1
//   M = cap latitude rows (theta=[0,π/2]), N = longitude cols
//
// Buffer sizes:
//   totalVerts = (M+2)*(N+1) + 1
//   totalFaces = M*N*2 + N = N*(2*M+1)
//
// Dispatch (all four entries are independent — no ordering requirement):
//   genCapGeom   ceil((M+1)/8)  × ceil((N+1)/8) × 1   workgroup(8,8,1)
//   genDiskGeom  ceil((N+2)/64) × 1             × 1   workgroup(64,1,1)
//   genCapFaces  ceil(M/8)      × ceil(N/8)     × 1   workgroup(8,8,1)
//   genDiskFaces ceil(N/64)     × 1             × 1   workgroup(64,1,1)

export const CAP_GEOM_WGSL  = /* wgsl */\`
${HEMI_CG}
\`;

export const DISK_GEOM_WGSL = /* wgsl */\`
${HEMI_DG}
\`;

export const CAP_FACES_WGSL = /* wgsl */\`
${HEMI_CF}
\`;

export const DISK_FACES_WGSL = /* wgsl */\`
${HEMI_DF}
\`;

export const GET_OUTPUT_METADATA_WGSL = /* wgsl */\`
${HEMI_OM}
\`;
JSEOF
echo "  → $OUT_HEMI"
echo ""
echo "Done."
